name: Lint and Test on PRs

on:
  pull_request:
    branches: [ main, develop ]

env:
  TR_NOTIFY_API_KEY: ${{ secrets.TR_NOTIFY_TEST_KEY }}
  JWT_KEY_GPG_PASSPHRASE: ${{ secrets.TR_JWT_KEY_GPG_PASSPHRASE }}

jobs:

  lint_and_test:
    name: Lint and Test the Project
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install all the pre-requisites
      run: npm ci

    - name: Check the linter
      run: npm run lint

    - name: Decrypt the secrets
      run: |
        chmod +x ./decrypt_secrets.sh
        ./decrypt_secrets.sh

    - name: Check the pre-start operations
      run: npm run prestart

    - name: Check the integration tests
      run: npm run test
